// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjectManagement.Data;

#nullable disable

namespace ProjectManagement.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230401184606_seeddata")]
    partial class seeddata
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "6dfe806f-05ca-4631-ae27-2c6ce99f5d66",
                            ConcurrencyStamp = "ea215117-d741-4028-9f1c-9d087abfb250",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = "89148659-c53d-407f-8f41-5075e948c420",
                            ConcurrencyStamp = "281b56ad-2682-4094-89f0-222b7acc2fa5",
                            Name = "Employee",
                            NormalizedName = "EMPLOYEE"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "875bd84b-4c10-4c0d-8a1d-0ccb03da22c6",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "3243f9e7-e9fb-4ba1-9459-924b1e41faf2",
                            Email = "admin@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@GMAIL.COM",
                            NormalizedUserName = "ADMIN@GMAIL.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEJoP4dl+YI3OhvMbDUZqM/dJ28tnsvmZpqzRsWQuAEEeWj/WLbqjNuiHqRSVcFS14A==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "a477b2ee-70d6-45be-983e-1d08e3b421a1",
                            TwoFactorEnabled = false,
                            UserName = "admin@gmail.com"
                        },
                        new
                        {
                            Id = "913294e3-e00b-4bea-b6c1-f31d163b3778",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "c687a243-948a-4763-8492-5527269c5992",
                            Email = "employee@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "EMPLOYEE@GMAIL.COM",
                            NormalizedUserName = "EMPLOYEE@GMAIL.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEKQeru9JFyPfYoGiikhcb7GKoRrIciHEcTXv618Wk7XZ50kWdZHv79uLbBl9QuytJA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "001d4a0d-1847-460b-9365-0cd73e040101",
                            TwoFactorEnabled = false,
                            UserName = "employee@gmail.com"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "875bd84b-4c10-4c0d-8a1d-0ccb03da22c6",
                            RoleId = "6dfe806f-05ca-4631-ae27-2c6ce99f5d66"
                        },
                        new
                        {
                            UserId = "913294e3-e00b-4bea-b6c1-f31d163b3778",
                            RoleId = "89148659-c53d-407f-8f41-5075e948c420"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("ProjectManagement.Models.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClientName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Client");
                });

            modelBuilder.Entity("ProjectManagement.Models.Consultant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<decimal>("BillingRate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("ClientId")
                        .HasColumnType("int");

                    b.Property<decimal>("CreditCardCost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("Date");

                    b.Property<decimal>("MarketingFee")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("MarketingManagerMemberId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("NetMargin")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PayRate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("PlacedByMemberId")
                        .HasColumnType("int");

                    b.Property<decimal>("PlacementFee")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("RecruiterMemberId")
                        .HasColumnType("int");

                    b.Property<decimal>("ReferralFees")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("ReferredByMemberId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("Date");

                    b.Property<decimal>("TeamLeadFee")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("TeamLeadMemberId")
                        .HasColumnType("int");

                    b.Property<int?>("TeamMemberId")
                        .HasColumnType("int");

                    b.Property<string>("UniqueConsultantId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("MarketingManagerMemberId");

                    b.HasIndex("PlacedByMemberId");

                    b.HasIndex("RecruiterMemberId");

                    b.HasIndex("ReferredByMemberId");

                    b.HasIndex("TeamLeadMemberId");

                    b.HasIndex("TeamMemberId");

                    b.ToTable("Consultants");
                });

            modelBuilder.Entity("ProjectManagement.Models.TeamMember", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TeamMembers");
                });

            modelBuilder.Entity("ProjectManagement.Models.TimeSheet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<decimal?>("AprBilling")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("AugBilling")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("ConsultantId")
                        .HasColumnType("int");

                    b.Property<decimal?>("DecBilling")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("FebBilling")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("JanBilling")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("JulBilling")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("JunBilling")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("MarBilling")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("MayBilling")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("NovBilling")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("OctBilling")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("SepBilling")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ConsultantId");

                    b.ToTable("Timesheets");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ProjectManagement.Models.Consultant", b =>
                {
                    b.HasOne("ProjectManagement.Models.Client", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId");

                    b.HasOne("ProjectManagement.Models.TeamMember", "MarketingManager")
                        .WithMany("MarketingManagerInConsultants")
                        .HasForeignKey("MarketingManagerMemberId");

                    b.HasOne("ProjectManagement.Models.TeamMember", "PlacedBy")
                        .WithMany("PlacedByInConsultants")
                        .HasForeignKey("PlacedByMemberId");

                    b.HasOne("ProjectManagement.Models.TeamMember", "Recruiter")
                        .WithMany("RecruiterInConsultants")
                        .HasForeignKey("RecruiterMemberId");

                    b.HasOne("ProjectManagement.Models.TeamMember", "ReferredBy")
                        .WithMany("ReferredByInConsultants")
                        .HasForeignKey("ReferredByMemberId");

                    b.HasOne("ProjectManagement.Models.TeamMember", "TeamLead")
                        .WithMany("TeamLeadInConsultants")
                        .HasForeignKey("TeamLeadMemberId");

                    b.HasOne("ProjectManagement.Models.TeamMember", "TeamMember")
                        .WithMany("TeamMemberInConsultants")
                        .HasForeignKey("TeamMemberId");

                    b.Navigation("Client");

                    b.Navigation("MarketingManager");

                    b.Navigation("PlacedBy");

                    b.Navigation("Recruiter");

                    b.Navigation("ReferredBy");

                    b.Navigation("TeamLead");

                    b.Navigation("TeamMember");
                });

            modelBuilder.Entity("ProjectManagement.Models.TimeSheet", b =>
                {
                    b.HasOne("ProjectManagement.Models.Consultant", "Consultant")
                        .WithMany()
                        .HasForeignKey("ConsultantId");

                    b.Navigation("Consultant");
                });

            modelBuilder.Entity("ProjectManagement.Models.TeamMember", b =>
                {
                    b.Navigation("MarketingManagerInConsultants");

                    b.Navigation("PlacedByInConsultants");

                    b.Navigation("RecruiterInConsultants");

                    b.Navigation("ReferredByInConsultants");

                    b.Navigation("TeamLeadInConsultants");

                    b.Navigation("TeamMemberInConsultants");
                });
#pragma warning restore 612, 618
        }
    }
}
